### ISSUE TITLE
Not compatible with Node >= v0.11

### ISSUE THREAD

**Issue by petermikitsh** [Adobe-Marketing-Cloud/marketing-cloud-node-sdk#1]
```
$ npm install https://github.com/Adobe-Marketing-Cloud/marketing-cloud-node-sdk/tarball/master

> node-expat@1.6.1 install /Users/pmikitsh/node_modules/marketing-cloud-node-sdk/node_modules/soap/node_modules/node-expat
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc:54:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args)
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:99:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Parse(const Arguments& args)
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:171:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> SetEncoding(const Arguments& args)
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:198:39: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> GetError(const Arguments& args)
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:212:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Stop(const Arguments& args)
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:229:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Resume(const Arguments& args)
                                    ^~~~~~~~~
                                    v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:244:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Reset(const Arguments& args)
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:272:51: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> GetCurrentLineNumber(const Arguments& args)
                                                  ^~~~~~~~~
                                                  v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:285:53: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> GetCurrentColumnNumber(const Arguments& args)
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:298:50: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> GetCurrentByteIndex(const Arguments& args)
                                                 ^~~~~~~~~
                                                 v8::internal::Arguments
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:22:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node-expat.cc:23:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value>
      (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/pmikitsh/.node-gyp/0.11.16/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../node-expat.cc:27:43: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)': type
      mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "parse", Parse);
                                          ^~~~~
/Users/pmikitsh/.node-gyp/0.11.16/src/node.h:246:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:28:49: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)': type
      mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "setEncoding", SetEncoding);
                                                ^~~~~~~~~~~
/Users/pmikitsh/.node-gyp/0.11.16/src/node.h:246:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:29:46: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)': type
      mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "getError", GetError);
                                             ^~~~~~~~
/Users/pmikitsh/.node-gyp/0.11.16/src/node.h:246:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:30:42: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)': type
      mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "stop", Stop);
                                         ^~~~
/Users/pmikitsh/.node-gyp/0.11.16/src/node.h:246:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:31:44: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)': type
      mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "resume", Resume);
                                           ^~~~~~
/Users/pmikitsh/.node-gyp/0.11.16/src/node.h:246:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:32:43: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)': type
      mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "reset", Reset);
                                          ^~~~~
/Users/pmikitsh/.node-gyp/0.11.16/src/node.h:246:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:33:58: error: cannot initialize a parameter of type 'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)': type
      mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "getCurrentLineNumber", GetCurrentLineNumber);
                                                         ^~~~~~~~~~~~~~~~~~~~
/Users/pmikitsh/.node-gyp/0.11.16/src/node.h:246:60: note: passing argument to parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pmikitsh/.nvm/v0.11.16/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/pmikitsh/.nvm/v0.11.16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pmikitsh/node_modules/marketing-cloud-node-sdk/node_modules/soap/node_modules/node-expat
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/pmikitsh/.nvm/v0.11.16/bin/node" "/Users/pmikitsh/.nvm/v0.11.16/bin/npm" "install" "https://github.com/Adobe-Marketing-Cloud/marketing-cloud-node-sdk/tarball/master"
npm ERR! node v0.11.16
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! node-expat@1.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@1.6.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pmikitsh/npm-debug.log
```

**Comment by davidbarratt** [comment]
ugh... I'm having a similar problem. :(

**Comment by petermikitsh** [comment]
@davidbarratt Looking at my error output, it seems like I may have had issues with my xcode installation. If you're on OS X, maybe you should double check your xcode config.

**Comment by RasmusFriis** [comment]
Same problem here, has anyone looked into this ?
